# Generated by Django 4.0.6 on 2023-04-24 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_year', models.PositiveIntegerField(default=1380)),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='students',
            name='lastname',
        ),
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='students',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.group'),
        ),
    ]
