# Generated by Django 4.0.6 on 2023-04-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_group_remove_students_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
